[Service]
ExecStartPre=/usr/bin/python3 /home/ubuntu/.local/libexec/blackbox-curator-config.py --config /home/ubuntu/.dkg/config.json --graph 0x37b1Fdfd134e2b17583bCBdD3034F91504cD9C70/agent-blackbox-vm
